name: Extract Amazon Titles

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install selenium pandas

    - name: Run scraper
      run: python test/extract_titles.py

    - name: Commit result
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add test/names.csv
        git commit -m "Update names.csv" || echo "No changes"
        git push
