name: Download CSV

on:
  schedule:
    - cron: "*/5 * * * *"  # Alle 5 Minuten
  workflow_dispatch:  # erlaubt manuelles Auslösen im GitHub UI

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download CSV
        run: |
          curl -L -o public/data.csv https://docs.google.com/spreadsheets/d/1Ft-FLTjhYD-vM6aYSpWxvz_xCjyB7hN8iANPBlcmLzE/export?format=csv

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/data.csv
          git commit -m "Update CSV" || echo "No changes to commit"
          git push
